import logging
import numpy as np

SEED = 0
OUTPUT_DIR = "./out"

# LOG_LEVEL = logging.INFO

# NUM_POOL_WORKERS = 32
# NUM_PREDICT_WORKERS = 2
# MAX_GAMES_PER_POOL_WORKER = 16
# TENSORFLOW_GPU_MEM_ALLOC_FRACT = (1.-0.30) / (NUM_PREDICT_WORKERS+1)
# TENSORFLOW_GPU_COUNT = 1
# TENSORFLOW_CPU_COUNT = 1

# NUM_GAMES = 128
# NUM_TRAIN_LOOP_ITER = 1000
# START_ITER = 7
# NUM_ITER = 10
# BATCH_SIZE = 256
# PREDICTION_QUEUE_BATCH_SIZE = 8

# STATE_HIST_SIZE = 8
# NUM_EVAL_GAMES = 9
# MIN_MODEL_REPLACEMENT_WIN_RATIO = 0.55 # 55%
# MCTS_STEPS = 100
# MAX_GAMES_HISTORY_SIZE = 20000
# # TRAIN_MODEL_FILE = "%s/model-train-ago-12051628-9x9-100-6-33.h5" % OUTPUT_DIR
# # SELF_PLAY_MODEL_FILE = "%s/model-best-ago-12051444-9x9-100-5-89.h5" % OUTPUT_DIR
# TRAIN_MODEL_FILE = None
# SELF_PLAY_MODEL_FILE = None

# PLAYER_1 = 0
# PLAYER_2 = 1
# EPS = 1e-8

# REWARD_DRAW = -1.0
# REWARD_WIN = 1.0
# REWARD_LOOSE = -1.0
# OUTCOME_DRAW = 0
# OUTCOME_WIN_PLAYER_1 = 1
# OUTCOME_WIN_PLAYER_2 = 2
# BOARD_SIZE = 9
# ZERO_TEMP_MOVE_INDEX = 15
# TEMPERATURES = [(0, ZERO_TEMP_MOVE_INDEX, 1.0), (ZERO_TEMP_MOVE_INDEX, np.inf, 1e-8)]
# TEMPERATURE_MIN = 1e-3

# ACTION_SPACE_SIZE = BOARD_SIZE*BOARD_SIZE+1
# DIRICHLET_ALPHA = 0.03
# ACT_NOISE_EPS = 0.25
# C_PUCT = 1.0

# CONV_FILTERS = 32
# CONV_KERNEL = (3, 3)
# NUM_RESIDUAL_BLOCKS = 4
# DENSE_SIZE = 32


# small board, fast training - debug:
LOG_LEVEL = logging.INFO

NUM_POOL_WORKERS = 3
NUM_PREDICT_WORKERS = 1
MAX_GAMES_PER_POOL_WORKER = 8
TENSORFLOW_GPU_MEM_ALLOC_FRACT = (1.-0.25) / (NUM_PREDICT_WORKERS+1)
TENSORFLOW_GPU_COUNT = 1
TENSORFLOW_CPU_COUNT = 1

NUM_GAMES = 4
NUM_TRAIN_LOOP_ITER = 200
START_ITER = 0
NUM_ITER = 3
BATCH_SIZE = 128
PREDICTION_QUEUE_BATCH_SIZE = 8
STATE_HIST_SIZE = 8
NUM_EVAL_GAMES = 5
MIN_MODEL_REPLACEMENT_WIN_RATIO = 0.00 # 55%
MCTS_STEPS = 15
MAX_GAMES_HISTORY_SIZE = 20000
TRAIN_MODEL_FILE = None
SELF_PLAY_MODEL_FILE = None


PLAYER_1 = 0
PLAYER_2 = 1
EPS = 1e-7

REWARD_DRAW = -1.0
REWARD_WIN = 1.0
REWARD_LOOSE = -1.0
OUTCOME_DRAW = 0
OUTCOME_WIN_PLAYER_1 = 1
OUTCOME_WIN_PLAYER_2 = 2
BOARD_SIZE = 5
ZERO_TEMP_MOVE_INDEX = 15
TEMPERATURES = [(0, ZERO_TEMP_MOVE_INDEX, 1.0), (ZERO_TEMP_MOVE_INDEX, np.inf, 1e-8)]
TEMPERATURE_MIN = 1e-3

ACTION_SPACE_SIZE = BOARD_SIZE*BOARD_SIZE+1
DIRICHLET_ALPHA = 0.03
ACT_NOISE_EPS = 0.25
C_PUCT = 1.0

CONV_FILTERS = 8
CONV_KERNEL = (3, 3)
NUM_RESIDUAL_BLOCKS = 2
DENSE_SIZE = 8


