import logging
import numpy as np
import datetime

SEED = 0
# LOG_LEVEL = logging.INFO

# NUM_POOL_WORKERS = 20
# NUM_PREDICT_WORKERS = 1
# MAX_GAMES_PER_POOL_WORKER = 4
# TENSORFLOW_GPU_MEM_ALLOC_FRACT = (1.-0.3) / (NUM_PREDICT_WORKERS+1)
# TENSORFLOW_GPU_COUNT = 1
# TENSORFLOW_CPU_COUNT = 2

# NUM_GAMES = 64
# NUM_TRAIN_LOOP_ITER = 300
# START_ITER = 0
# NUM_ITER = 20
# BATCH_SIZE = 256
# PREDICTION_QUEUE_BATCH_SIZE = NUM_POOL_WORKERS // NUM_PREDICT_WORKERS

# STATE_HIST_SIZE = 8
# NUM_EVAL_GAMES = 9
# MIN_MODEL_REPLACEMENT_WIN_RATIO = 0.55 # 55%
# MCTS_STEPS = 400
# MAX_GAMES_HISTORY_SIZE = 20000
# LOG_ID = "ago-v08-9x9-100"
# OUTPUT_DIR = "./out/%s" % LOG_ID
# #TRAIN_MODEL_FILE = "%s/model-train-16-33.h5" % OUTPUT_DIR
# #SELF_PLAY_MODEL_FILE = "%s/model-best-12-56.h5" % OUTPUT_DIR
# TRAIN_MODEL_FILE = None
# SELF_PLAY_MODEL_FILE = None

# PLAYER_1 = 0
# PLAYER_2 = 1
# EPS = 1e-8

# REWARD_DRAW = -1.0
# REWARD_WIN = 1.0
# REWARD_LOOSE = -1.0
# OUTCOME_DRAW = 0
# OUTCOME_WIN_PLAYER_1 = 1
# OUTCOME_WIN_PLAYER_2 = 2
# BOARD_SIZE = 9
# ZERO_TEMP_MOVE_INDEX = 15
# TEMPERATURES = [(0, ZERO_TEMP_MOVE_INDEX, 1.0), (ZERO_TEMP_MOVE_INDEX, np.inf, 1e-8)]
# TEMPERATURE_MIN = 1e-3

# ACTION_SPACE_SIZE = BOARD_SIZE*BOARD_SIZE+1
# DIRICHLET_ALPHA = 0.03
# ACT_NOISE_EPS = 0.25
# C_PUCT = 1.0

# CONV_FILTERS = 32
# CONV_KERNEL = (3, 3)
# NUM_RESIDUAL_BLOCKS = 4
# DENSE_SIZE = 32


# small board, fast training - debug:
LOG_LEVEL = logging.INFO

NUM_POOL_WORKERS = 20
NUM_PREDICT_WORKERS = 1
MAX_GAMES_PER_POOL_WORKER = 8
TENSORFLOW_GPU_MEM_ALLOC_FRACT = (1.-0.25) / (NUM_PREDICT_WORKERS+1)
TENSORFLOW_GPU_COUNT = 1
TENSORFLOW_CPU_COUNT = 1

NUM_GAMES = 64
NUM_TRAIN_LOOP_ITER = 300
START_ITER = 0
NUM_ITER = 5
BATCH_SIZE = 128
PREDICTION_QUEUE_BATCH_SIZE = 8
STATE_HIST_SIZE = 8
NUM_EVAL_GAMES = 5
MIN_MODEL_REPLACEMENT_WIN_RATIO = 0.55 # 55%
BOARD_SIZE = 5
MCTS_STEPS = 100
MAX_GAMES_HISTORY_SIZE = 20000
#LOG_ID = "ago-%s-%dx%d-%d" % (datetime.datetime.now().strftime("%m%d%H%M"), BOARD_SIZE, BOARD_SIZE, MCTS_STEPS)
LOG_ID = "ago-test-2"
OUTPUT_DIR = "./out/%s" % LOG_ID
# TRAIN_MODEL_FILE = "%s/model-train-1-20.h5" % OUTPUT_DIR
# SELF_PLAY_MODEL_FILE = "%s/model-best-1-20.h5" % OUTPUT_DIR
TRAIN_MODEL_FILE = None
SELF_PLAY_MODEL_FILE = None

PLAYER_1 = 0
PLAYER_2 = 1
EPS = 1e-8

REWARD_DRAW = -1.0
REWARD_WIN = 1.0
REWARD_LOOSE = -1.0
OUTCOME_DRAW = 0
OUTCOME_WIN_PLAYER_1 = 1
OUTCOME_WIN_PLAYER_2 = 2
ZERO_TEMP_MOVE_INDEX = 15
TEMPERATURES = [(0, ZERO_TEMP_MOVE_INDEX, 1.0), (ZERO_TEMP_MOVE_INDEX, np.inf, 1e-8)]
TEMPERATURE_MIN = 1e-3

ACTION_SPACE_SIZE = BOARD_SIZE*BOARD_SIZE+1
DIRICHLET_ALPHA = 0.03
ACT_NOISE_EPS = 0.25
C_PUCT = 1.0

CONV_FILTERS = 16
CONV_KERNEL = (3, 3)
NUM_RESIDUAL_BLOCKS = 4
DENSE_SIZE = 16



